
#taskfile for building the libraries for admin and clients and creating their packages

version: '3'

tasks:

  package-update:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
     - npm update

  build:
    cmds:
    #install deps and run build
    - npm install && npm run build
    
  #copy artifacts to temp directory
  postbuild_success:
    cmds:
    - powershell -Command "mkdir bin -Force"
    #tar the dist output and put it in the output dir
    - cd dist && tar -czf '../bin/release.tgz' .

  #clean hook
  clean:
    ignore_error: true
    cmds:
    - for: [ node_modules/, dist/, bin/ ]
      cmd: powershell -Command "Remove-Item -Recurse -Force {{.ITEM}}"

    - cmd: powershell -Command "Remove-Item release.tgz"