
#taskfile for building the libraries for admin and clients and creating their packages

version: '3'

tasks:

  package-update:
    dir: '{{ .USER_WORKING_DIR }}'
    cmds:
     - cmd: npm update

  build:
    cmds:
    #install deps and run build
    - cmd: npm install && npm run build

  #copy artifacts to temp directory
  postbuild_success:
    cmds:
    - cmd: powershell mkdir -Force bin
    #tar the dist output and put it in the output dir
    - cmd: cd dist && tar -czf '../bin/release.tgz' .

  #clean hook
  clean:
    ignore_error: true
    cmds:
    - for: [ node_modules/, dist/, bin/ ]
      cmd: powershell Remove-Item -Recurse -Force "{{ .ITEM }}"

    - cmd: powershell Remove-Item -Force release.tgz